//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle2DB_90_66
{
    using System;
    using System.Collections.Generic;
    
    public partial class CROSSCODE_CSHARP_90
    {
        public decimal USERID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PASSWORD { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
    }
}
